version: '3'
services:
  namenode:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    volumes:
      - namenode_data:/hadoop/dfs/name
    ports:
      - "9870:9870"
    environment:
      - CLUSTER_NAME=my-hadoop-cluster
    networks:
      - hadoop_net

  datanode:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    volumes:
      - datanode_data:/hadoop/dfs/data
    environment:
      - CLUSTER_NAME=my-hadoop-cluster
    networks:
      - hadoop_net

  resource_manager:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - hadoop_net

  node_manager:
    build:
      context: ./hadoop
      dockerfile: Dockerfile
    networks:
      - hadoop_net

volumes:
  namenode_data:
  datanode_data:

networks:
  hadoop_net:
